Feat(#95) housework info group member list
ghdcksgml1/N-bbang-housework pull request #102
Opened 2023-11-05 09:01 UTC by jusung-c

### 작업 내용
- [x] GROUP MEMBER 리스트 조회 API 구현

**테스트**
- [x] API 호출자가 해당 그룹원이 아닐 경우 예외가 발생한다.
- [x] groupMemberList API 호출시 GroupMemberListResponse 리스트가 잘 반환된다.

### 관련 이슈
#95

2023-11-05 11:03 UTC, jusung-c commented
<img width="755" alt="image" src="https://github.com/ghdcksgml1/N-bbang-housework/assets/62228433/ea670d97-cf6d-477a-a533-eed27585f844">

2023-11-06 00:30 UTC, ghdcksgml1 reviewed
고생하셨습니다 ㅎㅎ

2023-11-06 00:30 UTC, ghdcksgml1 commented on heachi-core/housework-api/src/main/java/com/heachi/housework/api/controller/group/member/GroupMemberController.java
> +        UserInfoResponse userInfoResponse = authExternalService.userAuthenticate(authorization);
ExternalAuthService에 그룹원인지 확인하는 메소드를 사용하는게 좋아보입니다! ㅎㅎ

2023-11-06 00:30 UTC, ghdcksgml1 commented on heachi-core/housework-api/src/main/java/com/heachi/housework/api/service/group/member/GroupMemberService.java
> +        boolean isGroupMember = groupMemberRepository.existsGroupMemberByUserEmailAndGroupInfoId(email, groupId);
위에 피드백대로 하시면 해당 부분은 제거하셔도 될 것 같아요

2023-11-06 00:30 UTC, ghdcksgml1 commented on heachi-core/housework-api/src/main/java/com/heachi/housework/api/controller/group/member/response/GroupMemberListResponse.java
> +public class GroupMemberListResponse {
List로 묶어 반환하는데 클래스명에 list가 들어가는게 어색하네요

2023-11-06 00:30 UTC, ghdcksgml1 commented on heachi-core/housework-api/src/main/java/com/heachi/housework/api/controller/group/member/GroupMemberController.java
> +@RequestMapping("/group")
RequestMapping : "/group" => "/group/member"

2023-11-06 13:25 UTC, jusung-c commented
피드백 감사합니다-!
수정 완료했습니다.

2023-11-06 14:48 UTC, ghdcksgml1 requested changes
고생하셨습니다 ! 요청사항 적용하고 바로 머지할게요

2023-11-06 14:48 UTC, ghdcksgml1 commented on heachi-core/housework-api/src/main/java/com/heachi/housework/api/service/group/member/GroupMemberService.java
> +    public List<GroupMemberResponse> selctGroupMember(Long groupId) {
앗 메소드명 오타 selct..

2023-11-06 14:48 UTC, ghdcksgml1 commented on heachi-core/housework-api/src/main/java/com/heachi/housework/api/controller/group/member/response/GroupMemberResponse.java
> +    public GroupMemberResponse(Long groupMemberId, String username) {
바꾸는 김에 public -> private으로 막아주세요

2023-11-06 15:02 UTC, merged