Feat(#105) housework info update
ghdcksgml1/N-bbang-housework pull request #117
Opened 2023-11-19 15:13 UTC by jusung-c

### 작업내용
- [x] 수정 Page 호출 API 구현
- [x] 수정 API 구현

### 테스트
- [x] 단건 집안일을 단건 집안일로 변경했을 경우 HouseworkTodo가 수정된다.
- [x] 단건 집안일을 비단건 집안일로 변경했을 경우 HouseworkTodo가 삭제되고 HouseworkInfo가 생성된다.
- [x] 비단건 집안일을 단건 집안일로 변경했을 경우 HouseworkInfo가 삭제되고 HouseworkTodo가 생성된다.
- [x] 비단건 집안일을 비단건 집안일로 변경했을 경우 이전의 HouseworkTodo들이 삭제되고 HouseworkInfo가 수정된다.

### 관련 이슈
#105

2023-11-22 06:31 UTC, jusung-c commented
### 수정 목록 
- [x] 스프링 시큐리티 권한 "CHEMIST", "CENTER" 제거
- [x] Housework 애플리케이션에 BaseEntity 인식을 위해 @EnableJpaAuditing 적용

2023-11-22 12:08 UTC, ghdcksgml1 requested changes
고생하셨습니다!! ㅎㅎ

2023-11-22 12:08 UTC, ghdcksgml1 commented on heachi-domain-mysql/src/main/java/com/heachi/mysql/define/housework/member/repository/HouseworkMemberRepository.java
> -    @Transactional
트랜잭션 어노테이션은 왜 삭제하신건가요??

2023-11-22 12:08 UTC, ghdcksgml1 commented on heachi-domain-mysql/src/main/java/com/heachi/mysql/define/housework/member/repository/HouseworkMemberRepositoryCustomImpl.java
> +    public boolean isSameHouseworkMemberIdAndGroupMemberId(HouseworkInfo info, List<Long> groupIdList) {
Interface의 파라미터명과 일치하지 않네요 ㅋㅋ

2023-11-23 07:14 UTC, jusung-c commented on heachi-domain-mysql/src/main/java/com/heachi/mysql/define/housework/member/repository/HouseworkMemberRepository.java
> -    @Transactional
이 메서드를 사용하는 서비스단에 이미 붙어있어서 호출하는 쪽의 트랜잭션에 묶여서 따로 붙여주지 않아도 될 줄 알았어요. 붙여야하는 걸까요??? 😅

2023-11-23 07:17 UTC, jusung-c commented on heachi-domain-mysql/src/main/java/com/heachi/mysql/define/housework/member/repository/HouseworkMemberRepositoryCustomImpl.java
> +    public boolean isSameHouseworkMemberIdAndGroupMemberId(HouseworkInfo info, List<Long> groupIdList) {
앗 😅

2023-11-23 07:21 UTC, jusung-c commented on heachi-domain-mysql/src/main/java/com/heachi/mysql/define/housework/member/repository/HouseworkMemberRepository.java
> -    @Transactional
단순 조회 기능이 아닌 삭제를 하는 메서드라서 안전하게 삭제하려면 붙여줘야 하겠군요!

2023-11-24 07:50 UTC, merged